# 5 useful Numpy functions!

Write a short introduction about Numpy and list the chosen functions. 

- Triganometric functions!
- Sorting!
- Ravel!
-  Can_convert!
- Angle conversions!

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian plotly --upgrade -q

In [20]:
import jovian
from plotly import graph_objects as go
from matplotlib import pylab as plt

In [3]:
filename="numpy-array-operations.ipynb"

In [15]:
#from plotly.com/python/table
def plot_diff(original,after):
 headerColor = 'grey'
 rowEvenColor = 'lightgrey'
 rowOddColor = 'white'
 return go.Figure(data=[go.Table(
    header=dict(
    values=['<b>Values</b>'],
    line_color='darkslategray',
    fill_color=headerColor,
    align=['left','center'],
    font=dict(color='white', size=12)
  ),
  cells=dict(
    values=[
      ['Original', 'After operation',],
      [original,after],
    ],
    line_color='darkslategray',
    # 2-D list of colors for alternating rows
    fill_color = [[rowOddColor,rowEvenColor,rowOddColor, rowEvenColor,rowOddColor]*5],
    align = ['left', 'center'],
    font = dict(color = 'darkslategray', size = 11)
    ))
])
def plot_curve(input, output, label):
  plt.plot(input,output)
  plt.xlabel("Angle(radians)")
  plt.ylabel(label)
  plt.axis("tight")
  plt.show()

In [7]:
jovian.commit(project='numpy-array-operations-z2p',filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
# List of functions explained
function1 = np.sin()
function2 = np.sort() 
function3 = np.ravel()
function4 = np.can_sort
function5 = np.deg2rad()

ValueError: invalid number of arguments

## Function 1 - Numpy Triganometry!

Perform triginometric functions in numpy, with the input in radians.

This section applies to sin,cos,tan,arcsin,arccos and arctan numpy functions.


In [31]:
random_radians=np.linspace(-2,2.2*np.pi,50)
print(random_radians.size)
random_sin=np.sin(random_radians)
plot_curve(random_radians,random_sin,"sin(x)")

50


All of the trigometric functions do an element-wise operation. Here, it was a sine operation on each element in the `random_radians` array.

### Example 2


In [33]:
random_cos=np.zeros(random_radians.size,)
np.cos(random_radians, out=random_cos,)
plot_curve(random_radians, random_cos, "cos(x)")

Another property of these functions is that you can optionally specify which numpy array to output the result to(the original values will be overwritten). By default, it will return a new numpy array. 

### Example 3 (breaking)

In [36]:
random_d=np.linspace(-10,5,50)
random_sin=np.tan(random_d)
plot_curve(random_d,random_tan,"tan(x)")

This is a semantic error. It breaks because the input values were in degrees, not radians, getting this weird graph

Overall, this function type is a must when dealing with trigonometry. Just make sure to have the angles in radians!

In [43]:
jovian.commit(filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

## Function 2 - np.sort()

Sort numpy arrays easily!
https://numpy.org/doc/stable/reference/generated/numpy.sort.html  

***Highly recommend to watch these two videos***  
    - https://www.youtube.com/watch?v=v4cd1O4zkGw - On BigO notation  
    - https://www.youtube.com/watch?v=KJuxI1BBLyQ - On the stability of algorithms   
There are 3 different kinds of sorting algorithms available, in order by average speed.  

| Algorithm | Speed | Stable| Comment |
| --- | --- | :-: | --- |
|Quicksort| O(n^2) | *false* | default sorting algorithm |
|Radix Sort| O(n^2) | **true**| Used on the backend in certain situations|
|Mergesort| O(n*log(n)) | **true**| Same as "stable"-Numpy will always choose the fastest stable sort for you  |
|Timsort| O(n*log(n))| **true**|  Currently cannot be called directly,use "stable"  |
|Heapsort | O(n*log(n))| *false*|

**Note from Docs-
The datatype determines which of ‘mergesort’ or ‘timsort’ is actually used, even if ‘mergesort’ is specified. User selection at a finer scale is not currently available.*

### Example 1 -working


In [54]:
random_array=np.random.randint(0,256,size=(10)) 
sorted_array=np.sort(a=random_array,kind="heapsort")

In [55]:
fig=plot_diff(original=random_array,after=sorted_array)
fig.show()

This example creates a single dimensional numpy array and sorts it with heapsort.
There is also a plotly table to help visualize the difference.   
(Pretty sure I could have used a dataframe, but still not there yet in the course.)

### Example 2 - working

In [56]:
random_array2=np.random.randint(0,2048,10)
sorted_array2=random_array2.copy()
sorted_array2.sort()
plot_diff(random_array2,sorted_array2)

Numpy also lets you sort an array in place using the .sort() method!

### Example 3 - breaking (to illustrate when it breaks)


In [60]:
random_array2.sort(kind="tinsort")
random_array2

ValueError: sort kind must be one of 'quick', 'heap', or 'stable' (got 'tinsort')

As stated in the docs, it is not possible to use tinsort directly.

This function makes it easy to be able to sort the data that you are working, especially when there are options(not dicussed here, but in docs) to sort catagorically and pick the sorting algorithm.

In [61]:
jovian.commit(filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

## Function 3 - np.ravel

This function is similar to np.flatten, but the difference is that np.ravel tries to return a view of the original array(meaning it just returns the original array- no copy) whenever possible(making it faster in some situations), unlike the flatten method, which returns a copy of the original array. Due to this behaviour, it is possible to modify the original array, so caution needs to be applied while using this.

### Example 1 - working


In [76]:
%time
random_array3=[np.random.randint(0,16,size=(2,4,6)),np.random.randn()]
raveled_array=np.ravel(random_array3)
print("Original")
print(random_array3)
print("Raveled")
print(raveled_array)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.82 µs
Original
[[[ 5 11  3  5  3  5]
  [ 9  8 11  6 11  6]
  [ 2 10 15  2 15 10]
  [ 5 15  4  4 13  4]]

 [[ 9  5  7  8  2 11]
  [13 11  3  9 15  0]
  [ 6 10 10  5 11 15]
  [ 8  7  5 10  2  3]]]
Raveled
[ 5 11  3  5  3  5  9  8 11  6 11  6  2 10 15  2 15 10  5 15  4  4 13  4
  9  5  7  8  2 11 13 11  3  9 15  0  6 10 10  5 11 15  8  7  5 10  2  3]


Ravel is a library level function- which means that it can work on lists of numpy arrays, while flatten is a operation for 1 single np array.

In [26]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Error: Failed to detect notebook filename. Please provide the correct notebook filename as the "filename" argument to "jovian.commit".


## Function 4 - np.can_cast

This is a small helper function that allows to check if a certain dtype can be converted into another dtype, 

In [42]:
np.can_cast(np.float32,np.float128)

True

This function takes an input dtype(`np.float32`) and an output dtype(`np.float128`)
The function returns a true when a cast can occur, and false when it can't. 

### Example 2

In [45]:
np.can_cast(np.int64,np.int8,"same_kind")

True

There is also 

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [36]:
jovian.commit()

NameError: name 'jovian' is not defined

## Function 5 - ???

Add some explanations

In [37]:
# Example 1 - working
???

Object `?` not found.


Explanation about example

In [38]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [40]:
jovian.commit()

NameError: name 'jovian' is not defined

## Conclusion

Summarize what was covered in this notebook, and where to go next

In [41]:
jovian.commit()

NameError: name 'jovian' is not defined