### **Assignment 2 - Numpy Array Operations**

 This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:

 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.

 The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

 Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.

**NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.

# 5 useful Numpy functions!

Write a short introduction about Numpy and list the chosen functions. 

- Triganometric functions!
- Sorting!
- Ravel!
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian plotly --upgrade -q

In [43]:
import jovian

<IPython.core.display.Javascript object>

In [44]:
filename="numpy-array-operations.ipynb"

In [52]:
#from plotly.com/python/table
import plotly.graph_objects as go
def plot_diff(original,after):
 headerColor = 'grey'
 rowEvenColor = 'lightgrey'
 rowOddColor = 'white'
 return go.Figure(data=[go.Table(
    header=dict(
    values=['<b>Values</b>'],
    line_color='darkslategray',
    fill_color=headerColor,
    align=['left','center'],
    font=dict(color='white', size=12)
  ),
  cells=dict(
    values=[
      ['Original', 'After operation',],
      [original,after],
    ],
    line_color='darkslategray',
    # 2-D list of colors for alternating rows
    fill_color = [[rowOddColor,rowEvenColor,rowOddColor, rowEvenColor,rowOddColor]*5],
    align = ['left', 'center'],
    font = dict(color = 'darkslategray', size = 11)
    ))
])


In [45]:
jovian.commit(project='numpy-array-operations-z2p',filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [46]:
import numpy as np

In [48]:
# List of functions explained 
function1 = np.sin()
"""
This function is one of many that follow the same rule
cos,tan,arcsin,arccos,arctan also follow the same pattern
"""
function2 = np.sort() 
function3 = np.ravel()
function4 = np.searchsorted()
function5 = np.partition()

ValueError: invalid number of arguments

## Function 1 - Numpy Triganometry!

Perform triginometric functions in numpy. 


This section applies to sin,cos,tan,arcsin,arccos and arctan numpy functions.


In [14]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [4]:
# Example 2 - working
???

Explanation about example

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [50]:
jovian.commit(filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

## Function 2 - np.sort()

Sort numpy arrays easily!
https://numpy.org/doc/stable/reference/generated/numpy.sort.html  

***Highly recommend to watch these two videos***  
    - https://www.youtube.com/watch?v=v4cd1O4zkGw - On BigO notation  
    - https://www.youtube.com/watch?v=KJuxI1BBLyQ - On the stability of algorithms   
There are 3 different kinds of sorting algorithms available, in order by average speed.  

| Algorithm | Speed | Stable| Comment |
| --- | --- | :-: | --- |
|Quicksort| O(n^2) | *false* | default sorting algorithm |
|Radix Sort| O(n^2) | **true**| Used on the backend in certain situations|
|Mergesort| O(n*log(n)) | **true**| Same as "stable"-Numpy will always choose the fastest stable sort for you  |
|Timsort| O(n*log(n))| **true**|  Currently cannot be called directly,use "stable"  |
|Heapsort | O(n*log(n))| *false*|

**Note from Docs-
The datatype determines which of ‘mergesort’ or ‘timsort’ is actually used, even if ‘mergesort’ is specified. User selection at a finer scale is not currently available.*

### Example 1 -working


In [54]:
random_array=np.random.randint(0,256,size=(10)) 
sorted_array=np.sort(a=random_array,kind="heapsort")

In [55]:
fig=plot_diff(original=random_array,after=sorted_array)
fig.show()

This example creates a single dimensional numpy array and sorts it with heapsort.
There is also a plotly table to help visualize the difference.   
(Pretty sure I could have used a dataframe, but still not there yet in the course.)

### Example 2 - working

In [56]:
random_array2=np.random.randint(0,2048,10)
sorted_array2=random_array2.copy()
sorted_array2.sort()
plot_diff(random_array2,sorted_array2)

Numpy also lets you sort an array in place using the .sort() method!

### Example 3 - breaking (to illustrate when it breaks)


In [60]:
random_array2.sort(kind="tinsort")
random_array2

ValueError: sort kind must be one of 'quick', 'heap', or 'stable' (got 'tinsort')

As stated in the docs, it is not possible to use tinsort directly.

This function makes it easy to be able to sort the data that you are working, especially when there are options(not dicussed here, but in docs) to sort catagorically and pick the sorting algorithm.

In [61]:
jovian.commit(filename=filename)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charitarthchugh/numpy-array-operations-z2p" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charitarthchugh/numpy-array-operations-z2p


'https://jovian.ml/charitarthchugh/numpy-array-operations-z2p'

## Function 3 - np.ravel

This function is similar to np.flatten, but the difference is that np.ravel tries to return a view of the original array(meaning it just returns the original array- no copy) whenever possible(making it faster in some situations), unlike the flatten method, which returns a copy of the original array. Due to this behaviour, it is possible to modify the original array, so caution needs to be applied while using this.

### Example 1 - working


In [76]:
%time
random_array3=[np.random.randint(0,16,size=(2,4,6)),np.random.randn()]
raveled_array=np.ravel(random_array3)
print("Original")
print(random_array3)
print("Raveled")
print(raveled_array)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.82 µs
Original
[[[ 5 11  3  5  3  5]
  [ 9  8 11  6 11  6]
  [ 2 10 15  2 15 10]
  [ 5 15  4  4 13  4]]

 [[ 9  5  7  8  2 11]
  [13 11  3  9 15  0]
  [ 6 10 10  5 11 15]
  [ 8  7  5 10  2  3]]]
Raveled
[ 5 11  3  5  3  5  9  8 11  6 11  6  2 10 15  2 15 10  5 15  4  4 13  4
  9  5  7  8  2 11 13 11  3  9 15  0  6 10 10  5 11 15  8  7  5 10  2  3]


Ravel is a library level function- which means that it can work on lists of numpy arrays, while flatten is a operation for 1 single np array.

In [26]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Error: Failed to detect notebook filename. Please provide the correct notebook filename as the "filename" argument to "jovian.commit".


## Function 3 - ???

Add some explanations

In [29]:
# Example 1 - working
???

Object `?` not found.


Explanation about example

In [30]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [32]:
jovian.commit()

NameError: name 'jovian' is not defined

## Function 4 - ???

Add some explanations

In [33]:
# Example 1 - working
???

Object `?` not found.


Explanation about example

In [34]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [36]:
jovian.commit()

NameError: name 'jovian' is not defined

## Function 5 - ???

Add some explanations

In [37]:
# Example 1 - working
???

Object `?` not found.


Explanation about example

In [38]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
???

Object `?` not found.


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [40]:
jovian.commit()

NameError: name 'jovian' is not defined

## Conclusion

Summarize what was covered in this notebook, and where to go next

In [41]:
jovian.commit()

NameError: name 'jovian' is not defined